"""fix_circular_imports_baseline

Revision ID: 182e15d62d39
Revises: 
Create Date: 2026-03-15 09:34:25.201670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182e15d62d39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logic', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icd10_code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('epidemiology_data', sa.JSON(), nullable=True),
    sa.Column('high_yield_notes', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('evidence_grade', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_diagnoses_name')
    )
    op.create_index('idx_diag_name', 'diagnoses', ['name'], unique=False)
    op.create_table('ecg_effects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_ecg_effects_name')
    )
    op.create_index('ix_ecg_effects_name', 'ecg_effects', ['name'], unique=False)
    op.create_table('guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_interventions_name')
    )
    op.create_index('idx_intervention_name', 'interventions', ['name'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_investigations_name')
    )
    op.create_index('idx_investigation_name', 'investigations', ['name'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_lab_tests_name')
    )
    op.create_index('ix_lab_tests_name', 'lab_tests', ['name'], unique=False)
    op.create_table('mechanisms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_mechanisms_name')
    )
    op.create_index('ix_mechanisms_name', 'mechanisms', ['name'], unique=False)
    op.create_table('presentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_presentations_name')
    )
    op.create_index('idx_pres_name', 'presentations', ['name'], unique=False)
    op.create_table('side_effects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_side_effects_name')
    )
    op.create_index('ix_side_effects_name', 'side_effects', ['name'], unique=False)
    op.create_table('signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_signs_name')
    )
    op.create_index('idx_sign_name', 'signs', ['name'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_symptoms_name')
    )
    op.create_index('idx_symptom_name', 'symptoms', ['name'], unique=False)
    op.create_table('therapeutic_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_therapeutic_class_name')
    )
    op.create_index('ix_therapeutic_class_name', 'therapeutic_classes', ['name'], unique=False)
    op.create_table('diagnosis_guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('guideline_id', sa.UUID(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guideline_id'], ['guidelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'guideline_id', name='uq_diagnosis_guideline')
    )
    op.create_table('diagnosis_interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'intervention_id', name='uq_diagnosis_intervention')
    )
    op.create_table('diagnosis_investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'investigation_id', name='uq_diagnosis_investigation')
    )
    op.create_table('diagnosis_signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('sign_id', sa.UUID(), nullable=False),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('specificity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sign_id'], ['signs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'sign_id', name='uq_diagnosis_sign')
    )
    op.create_table('diagnosis_symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('symptom_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'symptom_id', name='uq_diagnosis_symptom')
    )
    op.create_table('drugs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=True),
    sa.Column('chemical_class', sa.String(), nullable=True),
    sa.Column('therapeutic_class_id', sa.UUID(), nullable=True),
    sa.Column('mechanism_id', sa.UUID(), nullable=True),
    sa.Column('habit_forming', sa.Boolean(), nullable=False),
    sa.Column('pregnancy_category', sa.String(), nullable=True),
    sa.Column('lactation_safety', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['mechanism_id'], ['mechanisms.id'], ),
    sa.ForeignKeyConstraint(['therapeutic_class_id'], ['therapeutic_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generic_name', name='uq_drugs_generic_name'),
    sa.UniqueConstraint('name', name='uq_drugs_name')
    )
    op.create_index('ix_drugs_generic_name', 'drugs', ['generic_name'], unique=False)
    op.create_index('ix_drugs_mechanism_id', 'drugs', ['mechanism_id'], unique=False)
    op.create_index('ix_drugs_name', 'drugs', ['name'], unique=False)
    op.create_index('ix_drugs_therapeutic_class_id', 'drugs', ['therapeutic_class_id'], unique=False)
    op.create_table('presentation_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('likelihood_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presentation_id', 'diagnosis_id', name='uq_presentation_diagnosis')
    )
    op.create_table('red_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('urgency_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_drugs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('indication_type', sa.String(), nullable=True),
    sa.Column('clinical_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'drug_id', name='uq_diagnosis_drug')
    )
    op.create_table('drug_contraindication',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'condition_id', name='uq_drug_contraindication')
    )
    op.create_index('ix_drug_contraindication_condition_id', 'drug_contraindication', ['condition_id'], unique=False)
    op.create_index('ix_drug_contraindication_drug_id', 'drug_contraindication', ['drug_id'], unique=False)
    op.create_table('drug_disease',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'disease_id', name='uq_drug_disease')
    )
    op.create_index('ix_drug_disease_disease_id', 'drug_disease', ['disease_id'], unique=False)
    op.create_index('ix_drug_disease_drug_id', 'drug_disease', ['drug_id'], unique=False)
    op.create_table('drug_dosing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('adult_dose', sa.Text(), nullable=True),
    sa.Column('pediatric_dose', sa.Text(), nullable=True),
    sa.Column('renal_adjustment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_ecg_effect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('ecg_effect_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ecg_effect_id'], ['ecg_effects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'ecg_effect_id', name='uq_drug_ecg_effect')
    )
    op.create_index('ix_drug_ecg_effect_drug_id', 'drug_ecg_effect', ['drug_id'], unique=False)
    op.create_index('ix_drug_ecg_effect_ecg_effect_id', 'drug_ecg_effect', ['ecg_effect_id'], unique=False)
    op.create_table('drug_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_a_id', sa.UUID(), nullable=False),
    sa.Column('drug_b_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('clinical_effect', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('mechanism_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['drug_a_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_b_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mechanism_id'], ['mechanisms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_a_id', 'drug_b_id', name='uq_drug_interaction_pair')
    )
    op.create_index('ix_drug_interaction_drug_a_id', 'drug_interactions', ['drug_a_id'], unique=False)
    op.create_index('ix_drug_interaction_drug_b_id', 'drug_interactions', ['drug_b_id'], unique=False)
    op.create_table('drug_lab_effect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('lab_test_id', sa.UUID(), nullable=False),
    sa.Column('effect', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'lab_test_id', name='uq_drug_lab_effect')
    )
    op.create_index('ix_drug_lab_effect_drug_id', 'drug_lab_effect', ['drug_id'], unique=False)
    op.create_index('ix_drug_lab_effect_lab_test_id', 'drug_lab_effect', ['lab_test_id'], unique=False)
    op.create_table('drug_side_effect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('side_effect_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_effect_id'], ['side_effects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'side_effect_id', name='uq_drug_side_effect')
    )
    op.create_index('ix_drug_side_effect_drug_id', 'drug_side_effect', ['drug_id'], unique=False)
    op.create_index('ix_drug_side_effect_side_effect_id', 'drug_side_effect', ['side_effect_id'], unique=False)
    op.create_table('drug_substitutes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('substitute_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'substitute_name', name='uq_drug_substitute')
    )
    op.create_index('ix_drug_substitute_drug_id', 'drug_substitutes', ['drug_id'], unique=False)
    op.create_table('drug_uses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('indication', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drug_uses')
    op.drop_index('ix_drug_substitute_drug_id', table_name='drug_substitutes')
    op.drop_table('drug_substitutes')
    op.drop_index('ix_drug_side_effect_side_effect_id', table_name='drug_side_effect')
    op.drop_index('ix_drug_side_effect_drug_id', table_name='drug_side_effect')
    op.drop_table('drug_side_effect')
    op.drop_index('ix_drug_lab_effect_lab_test_id', table_name='drug_lab_effect')
    op.drop_index('ix_drug_lab_effect_drug_id', table_name='drug_lab_effect')
    op.drop_table('drug_lab_effect')
    op.drop_index('ix_drug_interaction_drug_b_id', table_name='drug_interactions')
    op.drop_index('ix_drug_interaction_drug_a_id', table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_index('ix_drug_ecg_effect_ecg_effect_id', table_name='drug_ecg_effect')
    op.drop_index('ix_drug_ecg_effect_drug_id', table_name='drug_ecg_effect')
    op.drop_table('drug_ecg_effect')
    op.drop_table('drug_dosing')
    op.drop_index('ix_drug_disease_drug_id', table_name='drug_disease')
    op.drop_index('ix_drug_disease_disease_id', table_name='drug_disease')
    op.drop_table('drug_disease')
    op.drop_index('ix_drug_contraindication_drug_id', table_name='drug_contraindication')
    op.drop_index('ix_drug_contraindication_condition_id', table_name='drug_contraindication')
    op.drop_table('drug_contraindication')
    op.drop_table('diagnosis_drugs')
    op.drop_table('red_flags')
    op.drop_table('presentation_diagnoses')
    op.drop_index('ix_drugs_therapeutic_class_id', table_name='drugs')
    op.drop_index('ix_drugs_name', table_name='drugs')
    op.drop_index('ix_drugs_mechanism_id', table_name='drugs')
    op.drop_index('ix_drugs_generic_name', table_name='drugs')
    op.drop_table('drugs')
    op.drop_table('diagnosis_symptoms')
    op.drop_table('diagnosis_signs')
    op.drop_table('diagnosis_investigations')
    op.drop_table('diagnosis_interventions')
    op.drop_table('diagnosis_guidelines')
    op.drop_index('ix_therapeutic_class_name', table_name='therapeutic_classes')
    op.drop_table('therapeutic_classes')
    op.drop_index('idx_symptom_name', table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index('idx_sign_name', table_name='signs')
    op.drop_table('signs')
    op.drop_index('ix_side_effects_name', table_name='side_effects')
    op.drop_table('side_effects')
    op.drop_index('idx_pres_name', table_name='presentations')
    op.drop_table('presentations')
    op.drop_index('ix_mechanisms_name', table_name='mechanisms')
    op.drop_table('mechanisms')
    op.drop_index('ix_lab_tests_name', table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index('idx_investigation_name', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('idx_intervention_name', table_name='interventions')
    op.drop_table('interventions')
    op.drop_table('guidelines')
    op.drop_index('ix_ecg_effects_name', table_name='ecg_effects')
    op.drop_table('ecg_effects')
    op.drop_index('idx_diag_name', table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_table('decision_rules')
    # ### end Alembic commands ###
