"""knowledge layer upgraded

Revision ID: 149ae2d8592f
Revises: b2c23874a8a3
Create Date: 2026-03-12 15:59:07.573033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149ae2d8592f'
down_revision: Union[str, Sequence[str], None] = 'b2c23874a8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_conditions_name')
    )
    op.create_index('ix_conditions_category', 'conditions', ['category'], unique=False)
    op.create_index('ix_conditions_name', 'conditions', ['name'], unique=False)
    op.create_table('ecg_effects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_ecg_effects_name')
    )
    op.create_index('ix_ecg_effects_name', 'ecg_effects', ['name'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_lab_tests_name')
    )
    op.create_index('ix_lab_tests_name', 'lab_tests', ['name'], unique=False)
    op.create_table('mechanisms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_mechanisms_name')
    )
    op.create_index('ix_mechanisms_name', 'mechanisms', ['name'], unique=False)
    op.create_table('therapeutic_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_therapeutic_class_name')
    )
    op.create_index('ix_therapeutic_class_name', 'therapeutic_classes', ['name'], unique=False)
    op.create_table('drug_contraindication',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'condition_id', name='uq_drug_contraindication')
    )
    op.create_index('ix_drug_contraindication_condition_id', 'drug_contraindication', ['condition_id'], unique=False)
    op.create_index('ix_drug_contraindication_drug_id', 'drug_contraindication', ['drug_id'], unique=False)
    op.create_table('drug_ecg_effect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('ecg_effect_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ecg_effect_id'], ['ecg_effects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'ecg_effect_id', name='uq_drug_ecg_effect')
    )
    op.create_index('ix_drug_ecg_effect_drug_id', 'drug_ecg_effect', ['drug_id'], unique=False)
    op.create_index('ix_drug_ecg_effect_ecg_effect_id', 'drug_ecg_effect', ['ecg_effect_id'], unique=False)
    op.create_table('drug_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_a_id', sa.UUID(), nullable=False),
    sa.Column('drug_b_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('clinical_effect', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('mechanism_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['drug_a_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_b_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mechanism_id'], ['mechanisms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_a_id', 'drug_b_id', name='uq_drug_interaction_pair')
    )
    op.create_index('ix_drug_interaction_drug_a_id', 'drug_interactions', ['drug_a_id'], unique=False)
    op.create_index('ix_drug_interaction_drug_b_id', 'drug_interactions', ['drug_b_id'], unique=False)
    op.create_table('drug_lab_effect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('lab_test_id', sa.UUID(), nullable=False),
    sa.Column('effect', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'lab_test_id', name='uq_drug_lab_effect')
    )
    op.create_index('ix_drug_lab_effect_drug_id', 'drug_lab_effect', ['drug_id'], unique=False)
    op.create_index('ix_drug_lab_effect_lab_test_id', 'drug_lab_effect', ['lab_test_id'], unique=False)
    op.add_column('diseases', sa.Column('icd10_code', sa.String(), nullable=True))
    op.alter_column('diseases', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.create_index('ix_diseases_name', 'diseases', ['name'], unique=False)
    op.create_index('ix_diseases_icd10_code', 'diseases', ['icd10_code'], unique=False)
    op.create_unique_constraint('uq_diseases_icd10', 'diseases', ['icd10_code'])
    op.create_unique_constraint('uq_diseases_name', 'diseases', ['name'])
    op.alter_column('drug_disease', 'drug_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('drug_disease', 'disease_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('drug_disease_drug_id_fkey', 'drug_disease', type_='foreignkey')
    op.drop_constraint('drug_disease_disease_id_fkey', 'drug_disease', type_='foreignkey')
    op.create_foreign_key(None, 'drug_disease', 'drugs', ['drug_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'drug_disease', 'diseases', ['disease_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_drug_disease_disease_id', 'drug_disease', ['disease_id'], unique=False)
    op.create_index('ix_drug_disease_drug_id', 'drug_disease', ['drug_id'], unique=False)
    op.create_unique_constraint('uq_drug_disease', 'drug_disease', ['drug_id', 'disease_id'])
    op.add_column('drug_side_effect', sa.Column('frequency', sa.String(), nullable=True))
    op.alter_column('drug_side_effect', 'drug_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('drug_side_effect', 'side_effect_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('drug_side_effect_drug_id_fkey', 'drug_side_effect', type_='foreignkey')
    op.drop_constraint('drug_side_effect_side_effect_id_fkey', 'drug_side_effect', type_='foreignkey')
    op.create_foreign_key(None, 'drug_side_effect', 'drugs', ['drug_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'drug_side_effect', 'side_effects', ['side_effect_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_drug_side_effect_drug_id', 'drug_side_effect', ['drug_id'], unique=False)
    op.create_index('ix_drug_side_effect_side_effect_id', 'drug_side_effect', ['side_effect_id'], unique=False)
    op.create_unique_constraint('uq_drug_side_effect', 'drug_side_effect', ['drug_id', 'side_effect_id'])
    op.alter_column('drug_substitutes', 'drug_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_drug_substitute_drug_id', 'drug_substitutes', ['drug_id'], unique=False)
    op.drop_constraint('drug_substitutes_drug_id_fkey', 'drug_substitutes', type_='foreignkey')
    op.create_foreign_key(None, 'drug_substitutes', 'drugs', ['drug_id'], ['id'], ondelete='CASCADE')

    # Deduplicate existing rows before adding the unique constraint
    op.execute(
        """
        WITH ranked AS (
            SELECT ctid, ROW_NUMBER() OVER (
                PARTITION BY drug_id, substitute_name ORDER BY id
            ) AS rn
            FROM drug_substitutes
        )
        DELETE FROM drug_substitutes d
        USING ranked r
        WHERE d.ctid = r.ctid
          AND r.rn > 1;
        """
    )

    op.create_unique_constraint('uq_drug_substitute', 'drug_substitutes', ['drug_id', 'substitute_name'])
    op.add_column('drugs', sa.Column('generic_name', sa.String(), nullable=True))
    op.add_column('drugs', sa.Column('therapeutic_class_id', sa.UUID(), nullable=True))
    op.add_column('drugs', sa.Column('mechanism_id', sa.UUID(), nullable=True))
    op.add_column('drugs', sa.Column('pregnancy_category', sa.String(), nullable=True))
    op.add_column('drugs', sa.Column('lactation_safety', sa.String(), nullable=True))
    op.alter_column('drugs', 'habit_forming',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('ix_drugs_generic_name', 'drugs', ['generic_name'], unique=False)
    op.create_index('ix_drugs_mechanism_id', 'drugs', ['mechanism_id'], unique=False)
    op.create_index('ix_drugs_therapeutic_class_id', 'drugs', ['therapeutic_class_id'], unique=False)

    # Ensure drug_uses FK cascades so dedup below can delete safely
    op.drop_constraint('drug_uses_drug_id_fkey', 'drug_uses', type_='foreignkey')
    op.create_foreign_key(
        None, 'drug_uses', 'drugs', ['drug_id'], ['id'], ondelete='CASCADE'
    )

    # Deduplicate existing drug records on (name) and (generic_name) before enforcing uniqueness
    op.execute(
        """
        WITH ranked AS (
            SELECT ctid, ROW_NUMBER() OVER (PARTITION BY name ORDER BY id) AS rn
            FROM drugs
            WHERE name IS NOT NULL
        )
        DELETE FROM drugs d
        USING ranked r
        WHERE d.ctid = r.ctid
          AND r.rn > 1;
        """
    )
    op.execute(
        """
        WITH ranked AS (
            SELECT ctid, ROW_NUMBER() OVER (PARTITION BY generic_name ORDER BY id) AS rn
            FROM drugs
            WHERE generic_name IS NOT NULL
        )
        DELETE FROM drugs d
        USING ranked r
        WHERE d.ctid = r.ctid
          AND r.rn > 1;
        """
    )

    op.create_unique_constraint('uq_drugs_generic_name', 'drugs', ['generic_name'])
    op.create_unique_constraint('uq_drugs_name', 'drugs', ['name'])
    op.create_foreign_key(None, 'drugs', 'therapeutic_classes', ['therapeutic_class_id'], ['id'])
    op.create_foreign_key(None, 'drugs', 'mechanisms', ['mechanism_id'], ['id'])
    op.drop_column('drugs', 'action_class')
    op.drop_column('drugs', 'therapeutic_class')
    op.add_column('side_effects', sa.Column('severity', sa.String(), nullable=True))
    op.alter_column('side_effects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_side_effects_name'), table_name='side_effects')
    op.create_index('ix_side_effects_name', 'side_effects', ['name'], unique=False)
    op.create_unique_constraint('uq_side_effects_name', 'side_effects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_side_effects_name', 'side_effects', type_='unique')
    op.drop_index('ix_side_effects_name', table_name='side_effects')
    op.create_index(op.f('ix_side_effects_name'), 'side_effects', ['name'], unique=True)
    op.alter_column('side_effects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('side_effects', 'severity')
    op.add_column('drugs', sa.Column('therapeutic_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('drugs', sa.Column('action_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drugs', type_='foreignkey')
    op.drop_constraint(None, 'drugs', type_='foreignkey')
    op.drop_constraint('uq_drugs_name', 'drugs', type_='unique')
    op.drop_constraint('uq_drugs_generic_name', 'drugs', type_='unique')
    op.drop_index('ix_drugs_therapeutic_class_id', table_name='drugs')
    op.drop_index('ix_drugs_mechanism_id', table_name='drugs')
    op.drop_index('ix_drugs_generic_name', table_name='drugs')
    op.alter_column('drugs', 'habit_forming',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('drugs', 'lactation_safety')
    op.drop_column('drugs', 'pregnancy_category')
    op.drop_column('drugs', 'mechanism_id')
    op.drop_column('drugs', 'therapeutic_class_id')
    op.drop_column('drugs', 'generic_name')
    op.drop_constraint('uq_drug_substitute', 'drug_substitutes', type_='unique')
    op.drop_index('ix_drug_substitute_drug_id', table_name='drug_substitutes')
    op.alter_column('drug_substitutes', 'drug_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_drug_side_effect', 'drug_side_effect', type_='unique')
    op.drop_index('ix_drug_side_effect_side_effect_id', table_name='drug_side_effect')
    op.drop_index('ix_drug_side_effect_drug_id', table_name='drug_side_effect')
    op.alter_column('drug_side_effect', 'side_effect_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('drug_side_effect', 'drug_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('drug_side_effect', 'frequency')
    op.drop_constraint('uq_drug_disease', 'drug_disease', type_='unique')
    op.drop_index('ix_drug_disease_drug_id', table_name='drug_disease')
    op.drop_index('ix_drug_disease_disease_id', table_name='drug_disease')
    op.alter_column('drug_disease', 'disease_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('drug_disease', 'drug_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_diseases_name', 'diseases', type_='unique')
    op.drop_constraint('uq_diseases_icd10', 'diseases', type_='unique')
    op.drop_index('ix_diseases_icd10_code', table_name='diseases')
    op.drop_index('ix_diseases_name', table_name='diseases')
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=True)
    op.alter_column('diseases', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('diseases', 'icd10_code')
    op.drop_index('ix_drug_lab_effect_lab_test_id', table_name='drug_lab_effect')
    op.drop_index('ix_drug_lab_effect_drug_id', table_name='drug_lab_effect')
    op.drop_table('drug_lab_effect')
    op.drop_index('ix_drug_interaction_drug_b_id', table_name='drug_interactions')
    op.drop_index('ix_drug_interaction_drug_a_id', table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_index('ix_drug_ecg_effect_ecg_effect_id', table_name='drug_ecg_effect')
    op.drop_index('ix_drug_ecg_effect_drug_id', table_name='drug_ecg_effect')
    op.drop_table('drug_ecg_effect')
    op.drop_index('ix_drug_contraindication_drug_id', table_name='drug_contraindication')
    op.drop_index('ix_drug_contraindication_condition_id', table_name='drug_contraindication')
    op.drop_table('drug_contraindication')
    op.drop_index('ix_therapeutic_class_name', table_name='therapeutic_classes')
    op.drop_table('therapeutic_classes')
    op.drop_index('ix_mechanisms_name', table_name='mechanisms')
    op.drop_table('mechanisms')
    op.drop_index('ix_lab_tests_name', table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index('ix_ecg_effects_name', table_name='ecg_effects')
    op.drop_table('ecg_effects')
    op.drop_index('ix_conditions_name', table_name='conditions')
    op.drop_index('ix_conditions_category', table_name='conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###
