"""normalized diagnosis-centric schema

Revision ID: 617d2b6a8573
Revises: bb421d6becc6
Create Date: 2026-03-13 06:43:53.388856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617d2b6a8573'
down_revision: Union[str, Sequence[str], None] = 'bb421d6becc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) copy diseases into diagnoses if missing
    op.execute(
        """
        INSERT INTO diagnoses (id, name, icd10_code)
        SELECT d.id, d.name, d.icd10_code
        FROM diseases d
        WHERE NOT EXISTS (
            SELECT 1 FROM diagnoses dx WHERE dx.id = d.id
        );
        """
    )

    # 2) retarget FKs to diagnoses
    op.drop_constraint(op.f('drug_contraindication_condition_id_fkey'), 'drug_contraindication', type_='foreignkey')
    op.create_foreign_key(None, 'drug_contraindication', 'diagnoses', ['condition_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint(op.f('drug_disease_disease_id_fkey'), 'drug_disease', type_='foreignkey')
    op.create_foreign_key(None, 'drug_disease', 'diagnoses', ['disease_id'], ['id'], ondelete='CASCADE')

    # 3) drop obsolete indexes then drop tables
    op.drop_index(op.f('ix_diseases_icd10_code'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.drop_table('diseases')

    op.drop_index(op.f('ix_conditions_category'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_name'), table_name='conditions')
    op.drop_table('conditions')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drug_disease', type_='foreignkey')
    op.create_foreign_key(op.f('drug_disease_disease_id_fkey'), 'drug_disease', 'diseases', ['disease_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'drug_contraindication', type_='foreignkey')
    op.create_foreign_key(op.f('drug_contraindication_condition_id_fkey'), 'drug_contraindication', 'conditions', ['condition_id'], ['id'], ondelete='CASCADE')
    op.create_table('conditions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('conditions_pkey')),
    sa.UniqueConstraint('name', name=op.f('uq_conditions_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_conditions_name'), 'conditions', ['name'], unique=False)
    op.create_index(op.f('ix_conditions_category'), 'conditions', ['category'], unique=False)
    op.create_table('diseases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('icd10_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('diseases_pkey')),
    sa.UniqueConstraint('icd10_code', name=op.f('uq_diseases_icd10'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('uq_diseases_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=False)
    op.create_index(op.f('ix_diseases_icd10_code'), 'diseases', ['icd10_code'], unique=False)
    # ### end Alembic commands ###
