"""knowledge graph tables

Revision ID: b2c23874a8a3
Revises: 239692d53aa3
Create Date: 2026-03-12 15:20:22.284526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c23874a8a3'
down_revision: Union[str, Sequence[str], None] = '239692d53aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=True)
    op.create_table('side_effects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_side_effects_name'), 'side_effects', ['name'], unique=True)
    op.create_table('drug_disease',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('disease_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_side_effect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('side_effect_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['side_effect_id'], ['side_effects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drug_side_effects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_side_effects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('drug_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('side_effect', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name=op.f('drug_side_effects_drug_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drug_side_effects_pkey'))
    )
    op.drop_table('drug_side_effect')
    op.drop_table('drug_disease')
    op.drop_index(op.f('ix_side_effects_name'), table_name='side_effects')
    op.drop_table('side_effects')
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.drop_table('diseases')
    # ### end Alembic commands ###
