"""complete cdss schema

Revision ID: bb421d6becc6
Revises: 149ae2d8592f
Create Date: 2026-03-13 06:19:34.658619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb421d6becc6'
down_revision: Union[str, Sequence[str], None] = '149ae2d8592f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logic', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_interventions_name')
    )
    op.create_index('idx_intervention_name', 'interventions', ['name'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_investigations_name')
    )
    op.create_index('idx_investigation_name', 'investigations', ['name'], unique=False)
    op.create_table('presentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_presentations_name')
    )
    op.create_index('idx_pres_name', 'presentations', ['name'], unique=False)
    op.create_table('signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_signs_name')
    )
    op.create_index('idx_sign_name', 'signs', ['name'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_symptoms_name')
    )
    op.create_index('idx_symptom_name', 'symptoms', ['name'], unique=False)
    op.create_table('diagnosis_guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('guideline_id', sa.UUID(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guideline_id'], ['guidelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'guideline_id', name='uq_diagnosis_guideline')
    )
    op.create_table('diagnosis_interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'intervention_id', name='uq_diagnosis_intervention')
    )
    op.create_table('diagnosis_investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'investigation_id', name='uq_diagnosis_investigation')
    )
    op.create_table('diagnosis_signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('sign_id', sa.UUID(), nullable=False),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('specificity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sign_id'], ['signs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'sign_id', name='uq_diagnosis_sign')
    )
    op.create_table('diagnosis_symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('symptom_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'symptom_id', name='uq_diagnosis_symptom')
    )
    op.create_table('presentation_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('likelihood_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presentation_id', 'diagnosis_id', name='uq_presentation_diagnosis')
    )
    op.create_table('red_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('urgency_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_drugs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('indication_type', sa.String(), nullable=True),
    sa.Column('clinical_rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'drug_id', name='uq_diagnosis_drug')
    )
    op.create_table('drug_dosing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('adult_dose', sa.Text(), nullable=True),
    sa.Column('pediatric_dose', sa.Text(), nullable=True),
    sa.Column('renal_adjustment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('diagnoses', sa.Column('icd10_code', sa.String(), nullable=True))
    op.add_column('diagnoses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('diagnoses', sa.Column('evidence_grade', sa.String(), nullable=True))
    op.alter_column('diagnoses', 'epidemiology_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('idx_diag_name', 'diagnoses', ['name'], unique=False)
    op.create_unique_constraint('uq_diagnoses_name', 'diagnoses', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_diagnoses_name', 'diagnoses', type_='unique')
    op.drop_index('idx_diag_name', table_name='diagnoses')
    op.alter_column('diagnoses', 'epidemiology_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('diagnoses', 'evidence_grade')
    op.drop_column('diagnoses', 'last_updated')
    op.drop_column('diagnoses', 'description')
    op.drop_column('diagnoses', 'icd10_code')
    op.drop_table('drug_dosing')
    op.drop_table('diagnosis_drugs')
    op.drop_table('red_flags')
    op.drop_table('presentation_diagnoses')
    op.drop_table('diagnosis_symptoms')
    op.drop_table('diagnosis_signs')
    op.drop_table('diagnosis_investigations')
    op.drop_table('diagnosis_interventions')
    op.drop_table('diagnosis_guidelines')
    op.drop_index('idx_symptom_name', table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index('idx_sign_name', table_name='signs')
    op.drop_table('signs')
    op.drop_index('idx_pres_name', table_name='presentations')
    op.drop_table('presentations')
    op.drop_index('idx_investigation_name', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('idx_intervention_name', table_name='interventions')
    op.drop_table('interventions')
    op.drop_table('guidelines')
    op.drop_table('decision_rules')
    # ### end Alembic commands ###
